package org.apache.commons.cli;

import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintWriter;
import java.io.StringWriter;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

public class HelpFormatterTest {

    private HelpFormatter formatter;
    private StringWriter out;
    private PrintWriter pw;
    private static final String EOL = System.getProperty("line.separator");

    @Before
    public void setUp() {
        formatter = new HelpFormatter();
        out = new StringWriter();
        pw = new PrintWriter(out);
    }

    // -------------------------------------------------------------
    // Test Getters / Setters (State & Configuration)
    // -------------------------------------------------------------

    @Test
    public void testGettersAndSetters() {
        formatter.setWidth(100);
        assertEquals(100, formatter.getWidth());

        formatter.setLeftPadding(5);
        assertEquals(5, formatter.getLeftPadding());

        formatter.setDescPadding(7);
        assertEquals(7, formatter.getDescPadding());

        formatter.setSyntaxPrefix("Syntax: ");
        assertEquals("Syntax: ", formatter.getSyntaxPrefix());

        formatter.setNewLine("\n");
        assertEquals("\n", formatter.getNewLine());

        formatter.setOptPrefix("/");
        assertEquals("/", formatter.getOptPrefix());

        formatter.setLongOptPrefix("//");
        assertEquals("//", formatter.getLongOptPrefix());

        formatter.setArgName("param");
        assertEquals("param", formatter.getArgName());
    }

    // -------------------------------------------------------------
    // Test Input Validation & Boundaries on printHelp
    // -------------------------------------------------------------

    @Test(expected = IllegalArgumentException.class)
    public void testPrintHelpNullCmdLineSyntaxThrowsException() {
        formatter.printHelp(pw, 80, null, "header", new Options(), 1, 3, "footer", true);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testPrintHelpEmptyCmdLineSyntaxThrowsException() {
        formatter.printHelp(pw, 80, "", "header", new Options(), 1, 3, "footer", true);
    }

    @Test
    public void testPrintHelpHeaderAndFooterVariations() {
        Options options = new Options();
        options.addOption("h", "help", false, "display help");

        // Case 1: Header and footer are valid strings
        formatter.printHelp(pw, 80, "app", "Header line", options, 1, 3, "Footer line", false);
        pw.flush();
        String result = out.toString();
        assertTrue("Header should be printed", result.contains("Header line"));
        assertTrue("Footer should be printed", result.contains("Footer line"));

        // Case 2: Header and footer are null
        out.getBuffer().setLength(0);
        formatter.printHelp(pw, 80, "app", null, options, 1, 3, null, false);
        pw.flush();
        result = out.toString();
        assertFalse(result.contains("Header line"));
        assertFalse(result.contains("Footer line"));

        // Case 3: Header and footer are whitespace only (trimmed length == 0)
        out.getBuffer().setLength(0);
        formatter.printHelp(pw, 80, "app", "   ", options, 1, 3, "\t \n", false);
        pw.flush();
        result = out.toString();
        assertFalse(result.contains("   " + EOL));
    }

    @Test
    public void testPrintHelpOverloadedMethodsToSystemOut() {
        Options options = new Options();
        options.addOption("v", false, "verbose mode");

        // Smoke-test overloaded methods that print to System.out without throwing exceptions
        formatter.printHelp("myapp", options);
        formatter.printHelp("myapp", options, true);
        formatter.printHelp("myapp", "header", options, "footer");
        formatter.printHelp("myapp", "header", options, "footer", true);
        formatter.printHelp(80, "myapp", "header", options, "footer");
        formatter.printHelp(80, "myapp", "header", options, "footer", true);
        formatter.printHelp(pw, 80, "myapp", "header", options, 2, 4, "footer");
    }

    // -------------------------------------------------------------
    // Test Usage Generation (printUsage, appendOptionGroup, appendOption)
    // -------------------------------------------------------------

    @Test
    public void testPrintUsageManualSyntax() {
        formatter.printUsage(pw, 80, "myApp -a -b <file>");
        pw.flush();
        String expected = "usage: myApp -a -b <file>" + EOL;
        assertEquals(expected, out.toString());
    }

    @Test
    public void testPrintUsageAutoGeneratedWithOptionsAndGroups() {
        Options options = new Options();

        // 1. Regular optional option
        Option optA = new Option("a", "all", false, "do all");
        options.addOption(optA);

        // 2. Required option with arg
        Option optF = new Option("f", "file", true, "target file");
        optF.setRequired(true);
        optF.setArgName("filename");
        options.addOption(optF);

        // 3. Long option only (null short opt)
        Option optLongOnly = new Option(null, "config", true, "config path");
        options.addOption(optLongOnly);

        // 4. Option with argument but null argName
        Option optNoArgName = new Option("x", false, "no arg name");
        optNoArgName.setArgs(1);
        optNoArgName.setArgName(null);
        options.addOption(optNoArgName);

        // 5. OptionGroup (not required)
        OptionGroup group1 = new OptionGroup();
        group1.setRequired(false);
        group1.addOption(new Option("s", "small"));
        group1.addOption(new Option("b", "big"));
        options.addOptionGroup(group1);

        // 6. OptionGroup (required)
        OptionGroup group2 = new OptionGroup();
        group2.setRequired(true);
        group2.addOption(new Option("m", "mode1"));
        group2.addOption(new Option("n", "mode2"));
        options.addOptionGroup(group2);

        formatter.printUsage(pw, 120, "demoApp", options);
        pw.flush();
        String usage = out.toString();

        // Verify elements rendered properly in usage string
        assertTrue("Usage must start with prefix and app name", usage.startsWith("usage: demoApp "));
        assertTrue("Optional option [-a] should be wrapped in brackets", usage.contains("[-a]"));
        assertTrue("Required option -f should NOT be wrapped in brackets", usage.contains("-f <filename>"));
        assertTrue("Long-only option should have -- prefix", usage.contains("[--config <arg>]"));
        assertTrue("Option group 1 (optional) must be wrapped in [] with | delimiter",
                usage.contains("[-b | -s]"));
        assertTrue("Option group 2 (required) must not be wrapped in [] and use | delimiter",
                usage.contains("-m | -n"));
    }

    // -------------------------------------------------------------
    // Test Options Rendering (renderOptions)
    // -------------------------------------------------------------

    @Test
    public void testRenderOptionsFormattingAndAlignment() {
        Options options = new Options();

        // Short + Long + Arg + Description
        Option opt1 = new Option("s", "server", true, "Server address");
        opt1.setArgName("host");
        options.addOption(opt1);

        // Long only without arg
        Option opt2 = new Option(null, "dry-run", false, "Execute dry run without modifications");
        options.addOption(opt2);

        // Short only with arg but no argName (defaults to space)
        Option opt3 = new Option("p", true, "Port number");
        opt3.setArgName(null);
        options.addOption(opt3);

        // Option without description
        Option opt4 = new Option("q", "quiet", false, null);
        options.addOption(opt4);

        formatter.printOptions(pw, 80, options, 2, 4);
        pw.flush();
        String rendered = out.toString();

        assertTrue(rendered.contains("  -s,--server <host>"));
        assertTrue(rendered.contains("     --dry-run"));
        assertTrue(rendered.contains("  -p "));
        assertTrue(rendered.contains("  -q,--quiet"));
    }

    // -------------------------------------------------------------
    // Test Text Wrapping & Boundary Limits (renderWrappedText & findWrapPos)
    // -------------------------------------------------------------

    @Test
    public void testRenderWrappedTextShortTextNoWrap() {
        StringBuffer sb = new StringBuffer();
        formatter.renderWrappedText(sb, 50, 0, "Short line of text.");
        assertEquals("Short line of text.", sb.toString());
    }

    @Test
    public void testRenderWrappedTextWithExplicitNewlinesAndTabs() {
        StringBuffer sb = new StringBuffer();
        String input = "Line 1\nLine 2\tTabbed content";
        formatter.renderWrappedText(sb, 80, 0, input);
        String expected = "Line 1" + EOL + "Line 2" + EOL + "Tabbed content";
        assertEquals(expected, sb.toString());
    }

    @Test
    public void testRenderWrappedTextMultiLineWithTabStop() {
        StringBuffer sb = new StringBuffer();
        String text = "The quick brown fox jumps over the lazy dog repeatedly to test multi-line wrapping functionality.";
        // Wrap width = 30, tab stop for next line = 4
        formatter.renderWrappedText(sb, 30, 4, text);
        String[] lines = sb.toString().split(EOL);

        assertTrue("Should wrap into multiple lines", lines.length > 1);
        for (int i = 1; i < lines.length; i++) {
            assertTrue("Subsequent lines should start with 4 spaces padding", lines[i].startsWith("    "));
        }
    }

    /**
     * Edge Case Targeting Defects4J Cli-8:
     * When a single word exceeds the specified width and continues to the end of the text,
     * findWrapPos should not throw StringIndexOutOfBoundsException when pos reaches text.length().
     */
    @Test
    public void testFindWrapPosLongWordExceedingWidthFaultCli8() {
        // Text contains a continuous word without whitespace that exceeds width
        String longText = "VeryLongUnbreakableWordExceedingWidth";
        int width = 10;

        try {
            int pos = formatter.findWrapPos(longText, width, 0);
            // If the bug is fixed, pos is -1 (cannot break before end)
            assertEquals(-1, pos);
        } catch (StringIndexOutOfBoundsException e) {
            fail("CLI-8 Defect Detected: StringIndexOutOfBoundsException occurred in findWrapPos: " + e.getMessage());
        }
    }

    @Test
    public void testFindWrapPosWithWhitespaceAfterWidth() {
        String text = "1234567890abcdef ghijkl";
        int width = 10;
        // Should find space after width position
        int pos = formatter.findWrapPos(text, width, 0);
        assertEquals(16, pos);
    }

    // -------------------------------------------------------------
    // Test Utility Methods (rtrim and createPadding)
    // -------------------------------------------------------------

    @Test
    public void testRtrim() {
        assertNull(formatter.rtrim(null));
        assertEquals("", formatter.rtrim(""));
        assertEquals("", formatter.rtrim("   "));
        assertEquals("", formatter.rtrim("\t\r\n "));
        assertEquals("abc", formatter.rtrim("abc"));
        assertEquals("abc", formatter.rtrim("abc   \t"));
        assertEquals("  abc", formatter.rtrim("  abc  "));
    }

    @Test
    public void testCreatePadding() {
        assertEquals("", formatter.createPadding(0));
        assertEquals(" ", formatter.createPadding(1));
        assertEquals("     ", formatter.createPadding(5));
    }

    // -------------------------------------------------------------
    // Test OptionComparator (Inner Class via Sorting)
    // -------------------------------------------------------------

    @Test
    public void testOptionComparatorSortingOrder() {
        Options options = new Options();
        options.addOption("z", "zebra", false, "z option");
        options.addOption("a", "apple", false, "a option");
        options.addOption("M", "mango", false, "M option");

        formatter.printUsage(pw, 80, "app", options);
        pw.flush();
        String result = out.toString();

        // OptionComparator sorts case-insensitively using getKey()
        int posA = result.indexOf("-a");
        int posM = result.indexOf("-M");
        int posZ = result.indexOf("-z");

        assertTrue("-a should come before -M", posA < posM);
        assertTrue("-M should come before -z", posM < posZ);
    }
}